baseurl = "/"
languageCode = "en-us"
title = "Code & Capital: The Aristide Approach"
# Enable gogle analytics by entering your tracking code
googleAnalytics = "UA-114578285-1"
# Remove this line if you use this theme for a real website.
# It allows you to preview the theme within the exampleSite folder
# with the hugo server command
# themesDir = "../.."
enableEmoji = true
DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
ignoreErrors = ["error-remote-getjson"]

[pagination]
  pagerSize = 5

[Languages]
  [Languages.en]
    weight = 10
	contentDir = "content/en"
	[Languages.en.params]
	  LanguageName = "English"
  [Languages.nl]
    weight = 20
	contentDir = "content/nl"
    [Languages.nl.params]
      site_description = "In this space, I dive into the intersection of technology, cybersecurity, and business growth, sharing insights and strategies from my personal experience. If you're curious about how cybersecurity fuels innovation or how venture capital is shaping the future of tech, this is the place for you."
      location = "Ergens in de Cloud"
	  site_author_description = "Cloud Security Hero"
	  LanguageName = "Nederlands"
      [Languages.nl.params.portfolio]
	    title = "Portfolio"
        subtitle = "Een niet-exhaustieve lijst van mijn eerdere werkervaringen."
		[Languages.nl.params.portfolio.modal]
		  client = "Cliënt"
		  date = "Datum"
		  category = "Categorie"
		  buttonText = "Afsluiten"

[permalinks]
	post = "/:year/:month/:title/index.html"
	
[sitemap]
    changefreq = "weekly"
    priority = 0.5

# Needed to render HTML in markdown files
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[blackfriday]
  hrefTargetBlank = true
	
[params]
  site_author = "Aristide Bouix"
  site_description = "In this space, I dive into the intersection of technology, cybersecurity, and business growth, sharing insights and strategies from my personal experience. If you're curious about how cybersecurity fuels innovation or how venture capital is shaping the future of tech, this is the place for you."
  location = "Somewhere in the Cloud"
	site_author_description = "Cloud Security Hero"
	disableSearch = false
	disableLanguageSwitchingButton = false
  # Enable comments powered by Disqus by entering your disqus shortname
  disqusShortname = "pachli-1"
  # Link custom assets relative to /static
    avatar = "img/profile-image.jpg"
    header_background = "img/desk.jpg"
    header_title = "Code & Capital: The Aristide Approach"
    copyright = "Aristide Bouix -- Powered by [Hugo](http://gohugo.io)"
	images = ["/img/desk.jpg"]
  custom_css = []
  custom_js  = []
  social = [
    { name = "twitter", url = "https://twitter.com/ArisvdZ" },
    { name = "github", url = "https://github.com/ArisBee" },
    { name = "instagram", url = "https://instagram.com/arisbcollection" },
    { name = "linkedin", url = "https://linkedin.com/in/aristide-bouix" },
    { name = "email", url = "mailto:webmaster@aristidebouix.cloud" }
  ]

    # Enable gogle analytics by entering your tracking code
    google_analytics = "G-M5QMME4DD1"

    # Set up your BCH donation address
    donation = "bitcoincash:qrlp6d4cje9t2j6fr83pdm9alwhqrfaytu6atzjcjl"
  [params.twitter]
		username = "ArisvdZ"

	[params.logo]
		url = "/img/profile-image.jpg"

	[params.image]
		url = "/img/desk.jpg"
  
  [privacy]
  # Privacy tweaks for used buil-in default templates
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = true
  # useSessionStorage = true # Not supported by GA4
  [privacy.twitter]
   disable = false
   enableDNT = true
   simple = false
  [privacy.vimeo]
   disable = false
   enableDNT = true
   simple = false
  [privacy.youtube]
   disable = false
   privacyEnhanced = true
	
  # Portfolio section
  [params.portfolio]
    enable = true
    # All projects defined in their own files. You can find example projects
    # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    title = "Portfolio"
    subtitle = "A nonexhaustive list of my past working experiences."

    [params.portfolio.modal]
      client = "Client"
      date = "Date"
      category = "Category"
      buttonText = "Close"

	
[outputFormats.Algolia]
	baseName = "algolia"
	isPlainText = true
	mediaType = "application/json"
	notAlternative = true

[params.algolia]
	vars = ["title", "summary", "date", "publishdate", "expirydate", "relpermalink"]
	params = ["categories", "tags"]

[outputs]
	home = [ "HTML", "RSS", "Algolia"]