# Example Mailchimp Configuration for config.toml
# Copy the [params.mailchimp] section to your main config.toml file

[params.mailchimp]
    enabled = true  # Set to true to enable the popup
    
    # Replace with your actual Mailchimp form URL
    # Get this from: Mailchimp → Audience → Signup forms → Embedded forms
    action_url = "https://yourdomain.us1.list-manage.com/subscribe/post?u=YOUR_USER_ID&id=YOUR_LIST_ID"
    
    # Customize the popup content
    popup_title = "Stay in the Loop!"
    popup_description = "Get the latest insights on technology, cybersecurity, and business growth delivered to your inbox."
    disclaimer = "No spam, unsubscribe anytime."
    
    # Anti-spam honeypot field name (change if needed)
    honeypot_name = "b_mailchimp_honeypot"
    
    # Optional: Add hidden fields to track signup source
    [[params.mailchimp.additional_fields]]
        name = "SOURCE"
        value = "website_popup"
    
    [[params.mailchimp.additional_fields]]
        name = "SIGNUP_TYPE"
        value = "popup"

# Multilingual example (if you have multiple languages)
[Languages.en.params.mailchimp]
    popup_title = "Stay in the Loop!"
    popup_description = "Get the latest insights on technology, cybersecurity, and business growth delivered to your inbox."
    disclaimer = "No spam, unsubscribe anytime."

[Languages.nl.params.mailchimp]
    popup_title = "Blijf op de hoogte!"
    popup_description = "Ontvang de laatste inzichten over technologie, cyberbeveiliging en bedrijfsgroei in je inbox."
    disclaimer = "Geen spam, altijd uitschrijven mogelijk."